language: java
sudo: required
branches:
  only:
    - main
jdk:
  - openjdk11
services:
- docker
before_install:
  - chmod +x ./mvnw
script:
  - mvn clean package -Dmaven.test.skip=true
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker image build ./ -t xdqingyuan/pigeon-server:latest
  - docker image push xdqingyuan/pigeon-server:latest