mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/qingyuan/course.pojo

aliyun:
  verifyCodeTemplateCode: SMS_205431840
  SignName: 鸽子窝
  accessKeySecret: VZEiKwqQnYtvK9up6FdUOolgeRdLbx
  accessKeyId: LTAI4FtHHhFxRXNGn8EGCY4r

spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: Gzsnb@666
    url: jdbc:mysql://39.96.114.221:3306/pigeon?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    password: Gzsnb@666
    host: 39.96.114.221
---
spring:
  profiles: release
logging:
  file:
    name: ./a-pigeon/pigeon.log
---
spring:
  profiles: dev
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
---